Artem work
ClevertecFrontendLab/krasped pull request #5
Opened 2024-03-27 12:45 UTC by krasped

2024-03-27 12:48 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 60%.
Общее количество тестов: 5.
Количество непройденных тестов: 2.

2024-03-27 15:45 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-27 15:48 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-27 15:54 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-27 16:03 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-27 16:05 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-27 16:12 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-27 16:25 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-27 16:32 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-27 16:40 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-27 16:59 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-27 17:10 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**buy-tariff-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/krasped/1711559454/buy-tariff-success_1440x900.png)
***
**default-profile-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/krasped/1711559454/default-profile-page_1440x900.png)
***
**default-settings-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/krasped/1711559454/default-settings-page_1440x900.png)
***
**feedbacks with photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/krasped/1711559454/feedbacks%20with%20photo_1440x900.png)
***
**modal-big-photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/krasped/1711559454/modal-big-photo_1440x900.png)
***
**profile-modal-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/krasped/1711559454/profile-modal-error_1440x900.png)
***
**profile-modal-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/krasped/1711559454/profile-modal-success_1440x900.png)
***
**settings-page-with-sider_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/krasped/1711559454/settings-page-with-sider_360x740.png)
***
**settings-pro-cards_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/krasped/1711559454/settings-pro-cards_360x740.png)
***
**settings-sider-pro_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/krasped/1711559454/settings-sider-pro_833x900.png)

2024-03-28 06:30 UTC, Xaky0105 requested changes

2024-03-28 06:30 UTC, Xaky0105 commented on src/pages/main-page/main-page.tsx
> +    //     refetch()
закомментированный код нужно удалить по всему приложению

2024-03-28 06:30 UTC, Xaky0105 commented on src/pages/profile-page/profile-page.tsx
> +        dispatch(logout())
хорошо бы статусы вынести в константы

2024-03-28 06:30 UTC, Xaky0105 commented on src/pages/profile-page/profile-page.tsx
> +          onCancel={() => closeFeedbackFrom()}
onCancel={closeFeedbackFrom}

2024-03-28 06:30 UTC, Xaky0105 commented on src/pages/profile-page/profile-page.tsx
> +export default ProfilePage;
лучше не экспортировать компоненты по дефолту

2024-03-28 06:30 UTC, Xaky0105 commented on src/pages/settings-page/settings-page.tsx
> +  const sendFeedback = (values: IFeedbackReq) => {
const sendFeedback = (values: IFeedbackReq) => addFeedbacks(values)

2024-03-28 07:25 UTC, krasped commented on src/pages/profile-page/profile-page.tsx
> +export default ProfilePage;
использую lazy() => и не смог почему то именованный экспорт использовать там

2024-03-28 07:33 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**buy-tariff-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/krasped/1711611201/buy-tariff-success_1440x900.png)
***
**default-profile-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/krasped/1711611201/default-profile-page_1440x900.png)
***
**default-settings-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/krasped/1711611201/default-settings-page_1440x900.png)
***
**feedbacks with photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/krasped/1711611201/feedbacks%20with%20photo_1440x900.png)
***
**modal-big-photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/krasped/1711611201/modal-big-photo_1440x900.png)
***
**profile-modal-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/krasped/1711611201/profile-modal-error_1440x900.png)
***
**profile-modal-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/krasped/1711611201/profile-modal-success_1440x900.png)
***
**settings-page-with-sider_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/krasped/1711611201/settings-page-with-sider_360x740.png)
***
**settings-pro-cards_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/krasped/1711611201/settings-pro-cards_360x740.png)
***
**settings-sider-pro_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/krasped/1711611201/settings-sider-pro_833x900.png)

2024-03-28 07:36 UTC, Xaky0105 approved these changes

2024-03-28 08:19 UTC, byshlata approved these changes

2024-03-28 08:22 UTC, krasped commented on src/components/navbar/desctop/desctop.tsx
>                    e.preventDefault();
Опиши поподробней что имеешь ввиду? Я не совсем понял. Компонент линк  вынести отдельно?

2024-03-28 08:30 UTC, merged